FROM alpine:3.18

# Install MariaDB
RUN apk update && apk add --no-cache \
    mariadb \
    mariadb-client \
    mariadb-server-utils \
    && mkdir -p /run/mysqld \
    && chown -R mysql:mysql /run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql

# Copy custom MariaDB configuration
COPY ./conf/my.cnf /etc/mysql/conf.d/custom.cnf

# Copy and set up initialization script
COPY ./tools/init-db.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init-db.sh

# Create mysql user
RUN addgroup -g 999 mysql && \
    adduser -u 999 -G mysql -h /var/lib/mysql -s /sbin/nologin -D mysql && \
    chown -R mysql:mysql /var/lib/mysql

USER mysql

ENTRYPOINT ["init-db.sh"]
