FROM alpine:3.18

# Install MariaDB
RUN apk update && apk add --no-cache \
    mariadb \
    mariadb-client \
    mariadb-server-utils \
    && mkdir -p /run/mysqld \
    && chown -R mysql:mysql /run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql

# Copy custom MariaDB configuration
COPY ./conf/my.cnf /etc/mysql/conf.d/custom.cnf

# Copy and set up initialization script
COPY ./tools/init-db.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init-db.sh

# No need to create mysql user/group as they're created by the mariadb package
RUN chown -R mysql:mysql /var/lib/mysql

USER mysql

ENTRYPOINT ["init-db.sh"]
