version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception_network
    env_file:
      - .env

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception_network:
    driver: bridge

/*
version: '3'
services:
  mariadb:
    build: ./requirements/mariadb 
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy 
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

        #BONUS PART
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  ftp-server:
    build: requirements/bonus/ftp_server
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - inception
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}


  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"

  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    restart: always
    networks:
      - inception

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rz/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rz/data/wordpress'

networks:
  inception:
    driver: bridge
*/